# Generated by Django 4.2.19 on 2025-09-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders_app", "0002_remove_contact_user_remove_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
